### ISSUE TITLE
Backend development to enable table for user configuration of Facets and columns.

### ISSUE THREAD

**Issue by markbasham** [SciCatProject/backend#604] opened 2023-07-19 14:36 UTC
## Issue Name
Backend development to enable table for user configuration of Facets and columns.

### Summary
The user configuration needs to be stored to the main Scicat database so that preferences for what columns can be seen, what facets can be filtered and the order and type of the metadata and scientific metadata sections.

**Comment by markbasham** [comment] 2023-07-20 09:56
![20230719_162507](https://github.com/SciCatProject/scicat-backend-next/assets/822780/ea920f24-1fbb-4f0e-a268-89e638384930)

**Comment by nitrosx** [comment] 2023-07-24 20:10
We can leverage the userSettings endpoint, but we need to expand the user settings to include such list
We will also need and endpoint for the defaults that is accessible only by admin users.
The defaults will be used for anonymous users and to set up the user settings the first time or when the user request to reset her settings to the default.
High level fields are standards, while metadata for default can only be set on metadata keys belonging to public datasets.

**Comment by nitrosx** [comment] 2023-07-24 20:17
To summarize, we need to refactor the following endpoints:
- POST users/{id}/settings
- GET users/{id}/settings
- POST users/settings/default
- GET users/settings/default

First two endpoints are accessible logged in and admins, while the last two only to admins

**Comment by nitrosx** [comment] 2024-05-06 14:46
@Ingvord are you currently working on this ticket? do you need help or will do a PR in the BE?

**Comment by nitrosx** [comment] 2024-05-06 14:49
@Ingvord are you currently working on this ticket? do you need help or will do a PR in the BE?

**Comment by nitrosx** [comment] 2024-05-06 14:50
Is this a duplicate of #616 ? or viceversa?

**Comment by Ingvord** [comment] 2024-05-07 12:00
@nitrosx I am slowly approaching :) This one definitely will be involved in my next steps. They way I see it - I will do a PR to this repo. 

Seems to me that #616 is a subtask to this one

**Closed as completed** 2024-08-21 08:49 UTC
Labels: enhancement, Release Search UI, feature
